name: firstapp
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.9.2

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.7
  get: ^4.7.2
  encrypt: ^5.0.3
  lottie: ^3.3.2
  dotlottie_loader: ^0.0.5
  google_fonts: ^6.3.2
  flutter_rating_bar: ^4.0.1
  iconsax: ^0.0.8
  sticky_headers: ^0.3.0+2
  stylish_bottom_bar: ^1.1.1
  supabase_flutter: ^2.10.3
  video_player: ^2.10.1
  dio: ^5.9.0
  sqflite: ^2.4.2
  flutter_chat_ui: ^2.11.1
  flutter_chat_types: ^3.6.2
  intl: ^0.20.2
  get_storage: ^2.1.1
  flutter_launcher_icons: ^0.14.4
  image_picker: ^1.2.1
  flutter_dotenv: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - .env
    - assets/dotlotties/
    - assets/image/
    - assets/image/logo/
    - lib/
    - lib/core/
    - lib/core/route/
    - lib/core/utils/
    - lib/core/utils/validator/
    - lib/core/utils/video_module/
    - lib/core/Services/
    - lib/core/Services/DataBaseService/
    - lib/core/Services/DataBaseService/CenterDataBase/
    - lib/core/Services/DataBaseService/CenterDataBase/Controller/
    - lib/core/Services/DataBaseService/GenericDataFetch/
    - lib/core/Services/SupaBaseService/
    - lib/core/Services/SupaBaseService/UserDataService/
    - lib/core/bindings/
    - lib/core/bindings/cartBinding/
    - lib/core/bindings/homeBindings/
    - lib/core/bindings/globalBinding/
    - lib/core/bindings/accountBinding/
    - lib/core/bindings/campaignBinding/
    - lib/core/bindings/shopDetailsBinding/
    - lib/core/bindings/productDeatailsBinding/
    - lib/core/Constants/
    - lib/data/
    - lib/data/local/
    - lib/data/local/LocalStorage/
    - lib/data/local/User_Session/
    - lib/data/local/EssentialData/
    - lib/data/models/
    - lib/data/models/mainDataModel/
    - lib/data/repository/
    - lib/data/repository/datafetchAbstraction/
    - lib/common/
    - lib/common/card/
    - lib/common/card/list/
    - lib/common/card/banner/
    - lib/common/card/widget/
    - lib/common/icon/
    - lib/common/text/
    - lib/common/image/
    - lib/common/button/
    - lib/common/textfield/
    - lib/exports/
    - lib/feature/
    - lib/feature/screens/
    - lib/feature/screens/auth/
    - lib/feature/screens/auth/login/
    - lib/feature/screens/auth/login/view/
    - lib/feature/screens/auth/login/controller/
    - lib/feature/screens/auth/widgets/
    - lib/feature/screens/auth/profileinfo/
    - lib/feature/screens/auth/profileinfo/infoprovide/
    - lib/feature/screens/auth/forgetscreen/
    - lib/feature/screens/auth/registration/
    - lib/feature/screens/auth/registration/view/
    - lib/feature/screens/auth/registration/controller/
    - lib/feature/screens/auth/Auth_implements/
    - lib/feature/screens/shop/
    - lib/feature/screens/shop/cart/
    - lib/feature/screens/shop/cart/widget/
    - lib/feature/screens/shop/home/
    - lib/feature/screens/shop/home/widgets/
    - lib/feature/screens/shop/home/widgets/appbar/
    - lib/feature/screens/shop/home/widgets/appbar/widget/
    - lib/feature/screens/shop/home/widgets/drawer/
    - lib/feature/screens/shop/home/widgets/drawer/widget/
    - lib/feature/screens/shop/home/widgets/bodypart/
    - lib/feature/screens/shop/home/Controller/
    - lib/feature/screens/shop/home/categories/
    - lib/feature/screens/shop/home/categories/widgets/
    - lib/feature/screens/shop/account/
    - lib/feature/screens/shop/account/widget/
    - lib/feature/screens/shop/account/widget/orderlist/
    - lib/feature/screens/shop/account/widget/orderlist/pages/
    - lib/feature/screens/shop/account/widget/orderlist/widgets/
    - lib/feature/screens/shop/campaign/
    - lib/feature/screens/shop/campaign/widget/
    - lib/feature/screens/shop/campaign/controller/
    - lib/feature/screens/shop/shopdetatils/
    - lib/feature/screens/shop/shopdetatils/view/
    - lib/feature/screens/shop/shopdetatils/widget/
    - lib/feature/screens/shop/productdetail/
    - lib/feature/screens/shop/productdetail/widgets/
    - lib/feature/ai_module/
    - lib/feature/intro_screen/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
flutter_icons:
  android: true
  ios: true
  image_path: "assets/image/logo/logo_black.png"
